### ISSUE TITLE
trigger nightly builds

### ISSUE THREAD

**Issue by ajohnstone** [jenkinsci/github-organization-folder-plugin#10]
I'm wondering about the best way to trigger nightly builds whilst using the github organisation plugin. Would be great if someone can provide a pointer.

**Comment by ssbarnea** [comment]
I am doing this currently manually which is a real PITA. Create a freetype jenkins job and add these jobs to it. Please keep in mind that the jobs names look like "orgnaame/jobs/repo/jobs/branch/name"

**Comment by jglick** [comment]
Use JIRA.
