### ISSUE TITLE
Support for github enterprise

### ISSUE THREAD

**Issue by ghost** [jenkinsci/github-organization-folder-plugin#11]
github organization plugin currently works only with the public github.com credentials. Is there a way, we can leverage same scanning capabilities for github enterprise as well?

**Comment by ajmenteng** [comment]
@ghost You need to firstly configure the GitHub Enterprise Servers in the System Configuration. The API for your GitHub enterprise will then appear in the API endpoint box in the GitHub organization setting. Fill the other options accordingly and you'll be ready to scan.

**Comment by dan-kirberger** [comment]
I'm having issues with Github Enterprise as well. Credentials (username + access token, username + password) that typically work elsewhere with github enterprise are not working with this plugin.

I simply see "Invalid scan credentials" in the scan log.

**Comment by freeman** [comment]
@dan-kirberger this is fixed by jenkinsci/github-branch-source-plugin#58 (which is not released yet but works well in my testing).

**Comment by jglick** [comment]
Use JIRA.
