### ISSUE TITLE
Unable to enable building or PR when list of branches to build is filtered.

### ISSUE THREAD

**Issue by ssbarnea** [jenkinsci/github-organization-folder-plugin#13]
I already raised this initially on http://stackoverflow.com/questions/37842537/how-to-build-a-selected-list-of-branches-and-pull-requests-using-jenkins-github but I am afraid that this is a bug: either this doesn't work or is totally undocumented. I already spend few good hours trying to find a solution for a simple issue.

The problem is that once I add the filter for the list of branches to build to master develop release* hotfix* Jenkins stops building PRs.

It does work as expected for these branches but I does not pull PRs made against them and this is mandatory as we want to be able to merge only code that was executed by Jenkins, but without having to include the source branches in the normal list of builds (we don't want to build each feature branch as they can get lots and lots of changes.)

So, how I am supposed to builds made for PRs made against the list of branches that I enabled using the filter?

**Comment by ssbarnea** [comment]
@kohsuke I also raised it on https://issues.jenkins-ci.org/browse/JENKINS-36352 but no feedback so far.

**Comment by jglick** [comment]
Use JIRA.
