### ISSUE TITLE
Jenkins does not build when webhook is hit

### ISSUE THREAD

**Issue by aneeshd16** [jenkinsci/github-organization-folder-plugin#18]
After installing this plugin, it automatically created  webhook in Github as expected. I did a `git push`, Github shows that a webhook was sent with a 200 response. Jenkins log shows that a hook was received. But no build was triggered.

**Comment by DeepDiver1975** [comment]
same here.

I defined a logger which logs
![bildschirmfoto von 2016-07-26 12-33-33](https://cloud.githubusercontent.com/assets/1005065/17134938/4d387628-532d-11e6-9db1-4dce606f514a.png)


But I never see org.jenkinsci.plugins.orgfolder.github.RepositoryGHEventSubscriber in the logger

**Comment by DeepDiver1975** [comment]
Getting closer - I guess .... why was no project triggered?

````
Jul 27, 2016 9:42:56 AM FINE org.jenkinsci.plugins.github_branch_source.GitHubWebhookListenerImpl

push event from DeepDiver1975 on github.com:owncloud/core did not match any project

**Comment by DeepDiver1975** [comment]
ha . case sensitivity issue as far as I can tell.
I used 'ownCloud' in the configuration of the organization - and not owncloud

**Comment by aneeshd16** [comment]
@DeepDiver1975 I had the same issue! Case sensitivity. I changed the name, and it works now. Thanks for the hints!
