### ISSUE TITLE
Ability to change columns in generated folders

### ISSUE THREAD

**Issue by brian-beckett-hp** [jenkinsci/github-organization-folder-plugin#21]
Hi,

Firstly, sorry if I'm filing this in the wrong place.

As a Jenkins admin, I would like to be able to configure what columns my GitHub Organisation Folders use, so that I can control what information is presented alongside the build job - e.g. what build slave was used, the test results, etc.

With manually created views and folders, it's possible to change the columns.  The only view that can't be edited is the built-in "All" view, which presumably uses some default set of columns.  The GitHub Organisation Folder-generated views match this default set.

It would be really nice if it were possible to define a set of columns to use in the generated views & subfolders.

Thanks - and thank you for this plugin, it's brilliant!

**Comment by jglick** [comment]
Please use JIRA.
