### ISSUE TITLE
Github webhook not triggering build

### ISSUE THREAD

**Issue by pdilyard** [jenkinsci/github-organization-folder-plugin#23]
I have a fresh instance of Jenkins with a single Github organization configured. I can manually scan the organization and everything works as expected. I configured the Github webhook plugin, and it automatically added a webhook to my organization. The webhook seems to be working fine: the expected actions are sent from Github to Jenkins and I get 200 OK responses, and Jenkins logs the following:
```
Received POST for https://github.com/[organization]/[repo]
```
However, no builds are triggered. I don't really see any other configuration options I haven't tried, so I'm really not sure what this problem is. Any help would be much appreciated!

**Comment by bmannix** [comment]
Could this be your issue? https://github.com/jenkinsci/github-organization-folder-plugin/issues/18

**Comment by pdilyard** [comment]
Wow...that was it, thanks!

For any future Googlers, make sure your organization is configured with the correct case-sensitivity. For example, if your organization is named `Acme` on Github, make sure it's configured as `Acme`, not `acme` in Jenkins.

Github and everyone else seems to treat repositories and owners as case-insensitive, so this should probably still be changed (or at the very list pointed out).

**Comment by paralin** [comment]
@pdilyard Thank you so much. It works great now that I fixed the casing!

**Comment by pdilyard** [comment]
😄
