### ISSUE TITLE
rebuilding a pr on failure

### ISSUE THREAD

**Issue by tmc** [jenkinsci/github-organization-folder-plugin#24]
If I re-run a jenkins job it's not updating the PR status check.

Should 'retest this please' comments on PRs re-trigger builds?

**Comment by ivanovit** [comment]
We also use comments to trigger PR builds by using [PR Builder Plugin](https://wiki.jenkins-ci.org/display/JENKINS/GitHub+pull+request+builder+plugin).

**Comment by sixty4k** [comment]
@ivanovit Does the PR Builder Plugin now work with Pipelines, last I checked they were very much not friends.

**Comment by jayceekay** [comment]
also curious about the above question

**Comment by dzsodzso63** [comment]
This would be important to us as well 
+1 for the "retest this please" option

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
