### ISSUE TITLE
Triggers the build but does not show the result 

### ISSUE THREAD

**Issue by danyaljj** [jenkinsci/github-organization-folder-plugin#25]
When I open a pull request I can see that it correctly triggers a run: 
![screen shot 2016-09-16 at 12 53 29 pm](https://cloud.githubusercontent.com/assets/2441454/18595944/8e9333f8-7c0c-11e6-89e0-37f08baf7415.png)

But it doesn't show in the PR itself: 
![screen shot 2016-09-16 at 12 57 14 pm](https://cloud.githubusercontent.com/assets/2441454/18595953/a0578ee0-7c0c-11e6-9076-eeffd2c6c4c4.png)

**Comment by ssbarnea** [comment]
Where you able to figure out how to enable this? My impression is that this plugin does not supports this but this is not an excuse for not providing information regarding how to enable this.

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
