### ISSUE TITLE
Custom Project Recognizers?

### ISSUE THREAD

**Issue by dustyburwell** [jenkinsci/github-organization-folder-plugin#35]
It looks like there's an extension point in this plugin for additional project recognizers. Could you point me to where in the code I can find the existing "Project Jenkinsfile" recognizer so I could see if it's reasonable to try to add a new one?

**Comment by sxmichael** [comment]
+1 for this

**Comment by Kegley** [comment]
Same! I've been doing some work with this would love to be able to specify a JSON file or similar.

**Comment by dustyburwell** [comment]
For what it's worth, we've started using a relatively simple DSL based on
Groovy custom libraries. Our Jenkinsfile looks like:

```groovy
build {
  name = "project-name"
  version = "1.0.0"
}
```

**Comment by Kegley** [comment]
Yeah, mine is already this simple as well. I'd still like to get rid of it completely! 

Any progress?

**Comment by imranansari** [comment]
+1

**Comment by albertvipe** [comment]
+1

**Comment by benzier** [comment]
No update here?

**Comment by pethers** [comment]
+1

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
* this sounds like a dev list question, not an “issue”

(BTW CloudBees Jenkins Enterprise includes this feature)
