### ISSUE TITLE
Custom Jenkinsfile name/location

### ISSUE THREAD

**Issue by akhy** [jenkinsci/github-organization-folder-plugin#37]
Is it possible? Jenkinsfile Project Recognizer seems need a little customization.

**Comment by juba895** [comment]
I'm also be interested in this issue!

**Comment by bmannix** [comment]
This would be very useful.  Currently the only way to support custom names/locations is to use the multi-branch plugin, however this requires each repository to be configured individually.

**Comment by justinharringa** [comment]
[PR #59 in the workflow-multibranch-plugin - version 2.15](https://github.com/jenkinsci/workflow-multibranch-plugin/pull/59) may have taken care of your needs.

**Comment by jglick** [comment]
Yes this is already possible. Furthermore (a) this plugin is obsolete, (b) we use JIRA not GitHub issues.
