### ISSUE TITLE
irregular naming on workspace directories

### ISSUE THREAD

**Issue by jdposthuma** [jenkinsci/github-organization-folder-plugin#38]
There seems to be a problem with the naming conventions of the project directories created in the $JENKINS_HOME/workspaces directory. My were automatically created as follows:

    -authentication_development-BCZ...@script
    erra-management_development-MIJT5...@script
    Intterra.ServerTools_master-FFRQ...@script
    ntterra.CustomersWeb_master-LW...@script

It appears to be unsuccessfully trying to use the naming convention `<repo>_<branch>-<sha>@script`

The repos in my case are actually named:

- intterra-authentication
- intterra-management
- Intterra.ServerTools
- Intterra.CustomersWeb

This behavior is on Jenkins 2.30, Branch API Plugin 1.11.1, and GitHub Organization Folder Plugin 1.5

**Comment by jdposthuma** [comment]
Looks like the problem has to do with a file name length limit.

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
