### ISSUE TITLE
Detecting New Repositories

### ISSUE THREAD

**Issue by rghunter** [jenkinsci/github-organization-folder-plugin#40]
Im not sure if this is a bug or simply a feature that doesn't exist:
Is this plugin supposed to be able to detect when new repositories are created and create jobs (sub jobs under the organization)? As far as I can tell from the logs, Jenkins receives a webhook call from github when a new repository is created. However, I can only get new repositories to be detected by running "rescan organization". This is less than optimal as calling this more than 1 or 2 times an hour exhausts our API limit with github. The webhooks work fine for triggering builds for existing multi branch jobs. It also detect branch creation and building fine as well.

Is this expected behavior? Should the gihub orgs plugin be able to create new sub jobs automatically from webhook calls? Or is that a feature yet to be implemented?

Thanks!

**Comment by pudge** [comment]
Bump.

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
