### ISSUE TITLE
Github hook doesn't trigger builds, despite correct org name case

### ISSUE THREAD

**Issue by racktear** [jenkinsci/github-organization-folder-plugin#42]
I've set up builds for our organization (Tarantool), but webhooks are not triggerting builds.

I see the following messages in logs:
```
INFO: Received PUSH for https://github.com/tarantool/doc
Feb 06, 2017 10:11:49 PM org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber onEvent
INFO: Received PushEvent for https://github.com/tarantool/doc
Feb 06, 2017 10:11:49 PM org.jenkinsci.plugins.github_branch_source.PushGHEventSubscriber onEvent
INFO: Received PUSH for https://github.com/tarantool/doc
```

I configured custom logger for events from:

```
org.jenkinsci.plugins.orgfolder.github.RepositoryGHEventSubscriber
org.jenkinsci.plugins.github.webhook.subscriber.DefaultPushGHEventSubscriber
```

But there are no errors there. I made sure that our organization name is typed in correct case (Tarantool). How can I debug what's happening?

**Comment by racktear** [comment]
I checked on a clean installation of Jenkins today. There is only a default set of recommended plugins. Still, hooks don't trigger new builds.

**Comment by racktear** [comment]
I did a bit more testing and tuns out the problem is somewhere in github-source plugin.  Here's the ticket:

https://issues.jenkins-ci.org/browse/JENKINS-41820

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
