### ISSUE TITLE
Trigger a job when master is updated?

### ISSUE THREAD

**Issue by jayceekay** [jenkinsci/github-organization-folder-plugin#43]
I know that this plugin can run jobs for all branches whenever they're updated, but I was looking for a solution for this use case:
1. trigger jobs when PRs are created and whenever those branches are updated
2. also trigger a job whenever the base branch (master) is updated

**Comment by SpencerMalone** [comment]
It used to have this functionality, but we just upgraded and this disappeared. I'm digging about to find out exactly when that stopped, I'll post here if I find it.

**Comment by irvingoe** [comment]
@SpencerMalone what version were you using before (when it was working) and also, was this working for Enterprise Github or public one?

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
