### ISSUE TITLE
Github Pipeline For BlueOcean still requires this plugin

### ISSUE THREAD

**Issue by chancez** [jenkinsci/github-organization-folder-plugin#44]
According to the change log in https://wiki.jenkins-ci.org/display/JENKINS/GitHub+Organization+Folder+Plugin, this plugin should be uninstallable, but it seems BlueOcean still depends on it. What's the expectation here with this? Should BlueOcean stop using this plugin and switch to the branch source plugin's APIs?

This is also mentioned in the blog post about scm-api v2, but given blueocean isn't moved, this feels like a bit of a mixed message.
https://jenkins.io/blog/2017/01/17/scm-api-2/:
>The functionality of this plugin has been migrated to the GitHub Branch Source plugin

**Comment by jglick** [comment]
We use JIRA not GitHub issues.
