### ISSUE TITLE
"Github hook trigger" not available as build trigger

### ISSUE THREAD

**Issue by alexcouper** [jenkinsci/github-organization-folder-plugin#45]
In other jobs on jenkins, my "Build Trigger" section looks like this:

![image](https://cloud.githubusercontent.com/assets/837734/24650548/11ddac0c-191a-11e7-8f55-41d47eaa9a48.png)

Inside a github organization folder, I only have 3 options:
![image](https://cloud.githubusercontent.com/assets/837734/24650587/286f9eda-191a-11e7-8925-bf96ef94f328.png)

And inside a job that was auto created by the organization folder, I have the same 3:
![image](https://cloud.githubusercontent.com/assets/837734/24650625/4513db0a-191a-11e7-9ef6-b3a7d84f2474.png)

My understanding is that I should be able to trigger builds of branches via a github webhook. I've set things up as described in [these docs](https://support.cloudbees.com/hc/en-us/articles/224543927-GitHub-webhook-configuration) but due to the lack of option in the folder i'm a bit stuck...

Any ideas what I'm missing to show the option there?

**Comment by bbaugher** [comment]
I also can't get this to work. My webhook is setup and being accepted, other non-pipeline/github org jobs can be built automatically but my jobs only get build if run manually or if I re-scan the org

**Comment by DarienFord** [comment]
I'm in a similar boat.  The org hook receives a 200 from jenkins, but nothing gets triggered.

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
* anyway this sounds like a users’ list question, not a bug report or feature request
