### ISSUE TITLE
Configure build notification?

### ISSUE THREAD

**Issue by eborgbjerg** [jenkinsci/github-organization-folder-plugin#47]
Hi, thanks for a nice plugin.

I have a question.
I got the Scan Organization and Jenkinsfile build working.
How can I configure email notification after a build ?
In a Freestyle Jenkins project, there is option of a post-build step for this, but I don't see that option in GitHub Organization project.

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
* anyway this sounds like a users’ list question, not a bug report or feature request
