### ISSUE TITLE
Would it be possible to build a auto-merge workflow using this plugin ?

### ISSUE THREAD

**Issue by mohanraj-r** [jenkinsci/github-organization-folder-plugin#48]
I am trying to migrate a job using the [jenkinsci/ghprb-plugin: github pull requests builder plugin for Jenkins](https://github.com/jenkinsci/ghprb-plugin) - which among other things has ability to merge PRs. Wondering if the GitHub Organization Folder plugin offers equivalent functionality ?

**Comment by edperry** [comment]
Glad I am not the only one with this question.

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
* anyway this sounds like a users’ list question
