### ISSUE TITLE
WebHook Data

### ISSUE THREAD

**Issue by edperry** [jenkinsci/github-organization-folder-plugin#49]
I can't seem to find anything documented but wanted to double check.

Are there Groovy variables besides the couple of ENV Variables passed the the Build Pipeline?

It would be nice to take some of the urls from the web request then to hardcore them.

**Comment by jglick** [comment]
* this plugin is obsolete
* we use JIRA not GitHub issues
* anyway this sounds like a users’ list question, not a bug report or feature request
