### ISSUE TITLE
Github API rate limit awareness

### ISSUE THREAD

**Issue by ptinsley** [jenkinsci/github-organization-folder-plugin#8]
The organization scanner needs to be updated to pay attention to the API quota left for a token, we have 246 repositories and who knows how many branches so it quickly exhausts the quota. Some kind of back-off logic is needed to keep from over-running the quota.

```
GitHub API rate limit exceeded

Aborted

Finished: ABORTED
```

**Comment by recena** [comment]
@ptinsley Could you file a Jira issue for that? I suppose you used a valid scan credencials, right?

**Comment by ptinsley** [comment]
missed the notification on this, sure I'll add one. Yes I did, it got quite a ways through the scan and then aborted, I only pasted in the error part.

**Comment by zot24** [comment]
@ptinsley did you add a Jira issue for this? and if yes, where is it? will be useful give as much info as possible when opening an issue so others could keep track on what's going on, thanks
